export enum UnitEnum {
  V = 'V',
  KV = 'Kv',
  A = 'A',
  HZ = 'Hz',
  C = 'C',
  W = 'W',
  KW = 'Kw',
  MW = 'Mw',
  KVAR = 'Kvar',
  MVAR = 'Mvar',
  KWH = 'Kwh',
  MOHM = 'MΩ',
  S = 'S',
  PERCENT = '٪',
  MS = 'Ms',
  MIN = 'Min',
  H = 'h',
  KG = 'Kg ',
  NA = 'N/A',
  KVARH = 'Kvarh',
  VDC = 'Vdc',
  VAC = 'Vac',
  M_PER_S = 'm/s',
  W_PER_M2 = 'W/m²',
  MJ_PER_M2 = 'MJ/m²',
  KWH_PER_M2 = 'KWh/m²',
}
