services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672' # AMQP protocol
      - '15672:15672' # Web management UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      
volumes:
  rabbitmq_data:
